name: Push to Main

on:
  push:
    branches: [xion/main]

permissions:
  contents: write
  deployments: write

jobs:
  cloudflare:
    uses: burnt-labs/github-workflows/.github/workflows/cloudflare-main.yml@511b72fad7c0bd937e2820b8e4165b075a875cf9 # v1.2.8
    secrets:
      cloudflare-account-id: ${{ secrets.BURNT_CLOUDFLARE_ACCOUNT_ID }}
      cloudflare-api-token: ${{ secrets.BURNT_CLOUDFLARE_API_TOKEN }}
