name: Push to Main

on:
  push:
    branches: [xion/main]

permissions:
  contents: write
  deployments: write

jobs:
  cloudflare:
    uses: burnt-labs/github-workflows/.github/workflows/cloudflare-main.yml@185554bd035d31757e526b90416eef9ed5ed56e1 # v1.2.0
    secrets:
      cloudflare-account-id: ${{ secrets.BURNT_CLOUDFLARE_ACCOUNT_ID }}
      cloudflare-api-token: ${{ secrets.BURNT_CLOUDFLARE_API_TOKEN }}
